### ISSUE TITLE
Run on PC and Apk file to run offline from phone

### ISSUE THREAD

**Issue by iuvi7** [qifi-dev/qrs#17]
Hi! Cool project :)

Please, explain, can i run it in offline mode from my Android device to send files without visiting website [qrss.netlify.app/](https://qrss.netlify.app/) ? And also how to run it on PC without internet? ("npm install" and "npm run dev" does not work)

If yes, how? Or maybe it possible to develop apk application to use on phone?

Thank you!

**Comment by LittleSound** [comment]
Using PWA technology, the web terminal can be used in an offline environment. for the CLI version, you can slso install it in advance and use it offline.

If you prefer APK, you can encapsulate one.

**Comment by iuvi7** [comment]
> Using PWA technology, the website can be used in an offline environment. for the CLI version, you can slso install it in advance and use it offline.
> 
> If you prefer APK, you can encapsulate one.

Okay, i made it works from phone by PWA, but it only works on streaming QR's...
So means - if i stream QR's on PC screen and capture them by phone it get 100% (all blocks green) but **no** download or anything else happens

Also, i don't get how to run it on PC without beeing on website online. I'm a daily user and may i ask instructions step by step? Thanks

**Comment by LittleSound** [comment]
> I'm a daily user and may i ask instructions step by step? 

This is an open-source project, and I welcome collaboration to improve it. 

However, my time is limited. so I‘m sorry, I have no obligation to provide such services for free.

>  i don't get how to run it on PC without beeing on website online.

You can use [the QiFi CLI](https://github.com/qifi-dev/qrs/tree/main/packages/cli) to do this

> So means - if i stream QR's on PC screen and capture them by phone it get 100% (all blocks green) but no download or anything else happens

I think there may have a bug. if you know how to fix it, you are welcome to try it and submit a PR. or create a new detailed Issue that can be reproduced.

**Comment by iuvi7** [comment]
Okay i made it works for both PC and Android in offline mode in both directions :) How can i contribute all of that to here? Thanks

**Comment by troilus** [comment]
> > Using PWA technology, the website can be used in an offline environment. for the CLI version, you can slso install it in advance and use it offline.
> > If you prefer APK, you can encapsulate one.
> 
> Okay, i made it works from phone by PWA, but it only works on streaming QR's... So means - if i stream QR's on PC screen and capture them by phone it get 100% (all blocks green) but **no** download or anything else happens
> 
> Also, i don't get how to run it on PC without beeing on website online. I'm a daily user and may i ask instructions step by step? Thanks

sudo npm install -g pnpm
git clone https://github.com/qifi-dev/qrs.git
cd qrs
pnpm install
pnpm build
node .output/server/index.mjs  

Visti 127.0.0.1:3000 in your browser.

**Comment by iuvi7** [comment]
> > > Using PWA technology, the website can be used in an offline environment. for the CLI version, you can slso install it in advance and use it offline.
> > > If you prefer APK, you can encapsulate one.
> > 
> > 
> > Okay, i made it works from phone by PWA, but it only works on streaming QR's... So means - if i stream QR's on PC screen and capture them by phone it get 100% (all blocks green) but **no** download or anything else happens
> > Also, i don't get how to run it on PC without beeing on website online. I'm a daily user and may i ask instructions step by step? Thanks
> 
> sudo npm install -g pnpm git clone https://github.com/qifi-dev/qrs.git cd qrs pnpm install pnpm build node .output/server/index.mjs
> 
> Visti 127.0.0.1:3000 in your browser.

Thank you very very much! It's exactly what i mean :) 

Would be cool for author's to add it to release "Readme.md" file

P.S. How can i share\contribute my HTML file to this project? So anyone can download it and it works universal for any platform PC\Phone :)

**Comment by troilus** [comment]
> > > > Using PWA technology, the website can be used in an offline environment. for the CLI version, you can slso install it in advance and use it offline.
> > > > If you prefer APK, you can encapsulate one.
> > > 
> > > 
> > > Okay, i made it works from phone by PWA, but it only works on streaming QR's... So means - if i stream QR's on PC screen and capture them by phone it get 100% (all blocks green) but **no** download or anything else happens
> > > Also, i don't get how to run it on PC without beeing on website online. I'm a daily user and may i ask instructions step by step? Thanks
> > 
> > 
> > sudo npm install -g pnpm git clone https://github.com/qifi-dev/qrs.git cd qrs pnpm install pnpm build node .output/server/index.mjs
> > Visti 127.0.0.1:3000 in your browser.
> 
> Thank you very very much! It's exactly what i mean :)
> 
> Would be cool for author's to add it to release "Readme.md" file
> 
> P.S. How can i share\contribute my HTML file to this project? So anyone can download it and it works universal for any platform PC\Phone :)

You can put the files in .\.output\public into a html server.

**Comment by LittleSound** [comment]
> Would be cool for author's to add it to release "Readme.md" file

Welcome to add it to README file

**Comment by iuvi7** [comment]
Thanks i will do both ;)
